travis:
  secure:
    BINSTAR_TOKEN: S1bYO2Hp7X/6EsalFZu4Jdw/fuKgtHNE7TGMl8CJzegyZMUCIDPPJkjyOHE0NQev1PSnSDBuoBE9Jp0r75p99KIWWT176Q+7kqqzXZoYMkx2wfUCBz5GL8ZDHoIhON5qnUGsvQFz22wQZh+HTVUMOOcAR3NxzyHpeTgfmb09DGMwiF5RPIFNBZ+tMP4qIS/Sem+f+RzmAx/r8MA/ty/vfow3VZC0TMGEqEjMoeQmTwtzYNdYZnZ7g4vfWCkReCO6H6jaG8WhxOVoO6TKEJdt8bOjwaxbvSwUEL0u10zh4Q3h9H+XlLKpNTQoN7y0kIPO4uEqgB0nQm+DO+emHZCFsNk176bbGOcymAsbs0g59nRSv1Xp6xpHWMpxFNYfNNC0ujcKRnnCgTcY4g0omDk2gg1XFCtMZl06IQy07Jb0rwxhMpWIwDgG6AdiU/RXHuoObeyZ6wnnIjUbcW9GKGOf6GD0O+mIVJ1xOEYTrfcvXOPg6JR16mvGaLP5yiT54LItQCWwEQbfZJif6NBLWtUtGumEVTpGFuJgdtRKa3YEnBDxtJwgE9zjYXrvjyEwfiClDPgMuQeRT0cblEcDoCgT9Y1SPagZ0FJjPr3Ef0nPx7DfTM8StUHjdtkup5Chz/NOnUJdfuUsoRBRJi54c2ESMzX3gZkEOc2c/33cIAOymPk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
